Study token login in sso
e-ucm/simva-unity-plugin pull request #2
Opened 2024-11-27 10:52 UTC by imartinezortiz

2025-04-25 18:53 UTC, Victorma requested changes
This is a great progress so far. There are a couple things I would like you to review but great work!

2025-04-25 18:53 UTC, Victorma commented on Runtime/Runner/SimvaManager.cs
> +                    NotifyManagers("Failed to Login with this token");
Add a SimvaPlugin.Instance error log of the error for debugging.

2025-04-25 18:53 UTC, Victorma commented on Runtime/Runner/SimvaManager.cs
> +                    NotifyManagers("Failed to Login with this token");
Add a SimvaPlugin.Instance error log of the error for debugging.

2025-04-25 18:53 UTC, Victorma commented on Runtime/Runner/SimvaManager.cs
> +                            if(API.SimvaConf.HomePage != null) {
Use String.IsNullOrEmpty instead

2025-04-25 18:53 UTC, Victorma commented on Runtime/Util/RequestsUtil.cs
> +            while (webRequest.result != UnityWebRequest.Result.ConnectionError && webRequest.result != UnityWebRequest.Result.ProtocolError && webRequest.downloadProgress != 1)
This should be done using the #if UNITY_2022_OR_NEWER and have an else with the old code

2025-04-25 18:53 UTC, Victorma commented on Runtime/Util/RequestsUtil.cs
> +            if (webRequest.result == UnityWebRequest.Result.ConnectionError || webRequest.result == UnityWebRequest.Result.ProtocolError)
This should be done using the #if UNITY_2022_OR_NEWER and have an else with the old code

2025-04-25 18:53 UTC, Victorma commented on Samples~/Demo/SimvaGameplayTester.cs
> +public class SimvaGameplayTester : MonoBehaviour
Namespace should be kept

2025-04-25 18:53 UTC, Victorma commented on Runtime/SimvaPlugin.cs
> +            RunScene("gameplay");
Should use uppercase as naming convention

2025-04-25 18:53 UTC, Victorma commented on Runtime/SimvaPlugin.cs
> +                case "gameplay":
Should use uppercase as naming convention

2025-04-25 18:53 UTC, Victorma commented on Runtime/SimvaPlugin.cs
> +            Log(name);
This log should be more descriptive like "Running scene: " + name

2025-04-25 18:53 UTC, Victorma commented on Runtime/SimvaPlugin.cs
> +            Log("[SIMVA] Starting...");
Remove [SIMVA] as log already has [SimvaUnityPlugin] Prefix

2025-04-25 18:53 UTC, Victorma commented on Runtime/SimvaPlugin.cs
> +                Log("[SIMVA] Conf Loaded...");
Remove [SIMVA] as log already has [SimvaUnityPlugin] Prefix

2025-04-25 18:53 UTC, Victorma commented on Runtime/SimvaPlugin.cs
> +                    Log("[SIMVA] Study is not set! Running the game without Simva...");
Remove [SIMVA] as log already has [SimvaUnityPlugin] Prefix

2025-04-25 18:53 UTC, Victorma commented on Runtime/SimvaPlugin.cs
> +                    Log("[SIMVA] Study is not set! Stopping...");
Remove [SIMVA] as log already has [SimvaUnityPlugin] Prefix

2025-04-25 18:53 UTC, Victorma commented on Runtime/SimvaPlugin.cs
> +                Log("[SIMVA] Simva is already started...");
Remove [SIMVA] as log already has [SimvaUnityPlugin] Prefix

2025-04-25 18:53 UTC, Victorma commented on Runtime/SimvaPlugin.cs
> +                Log("[SIMVA] Setting current target to Simva.Login...");
Remove [SIMVA] as log already has [SimvaUnityPlugin] Prefix

2025-04-25 18:53 UTC, Victorma commented on Runtime/SimvaPlugin.cs
> -                SceneManager.LoadSceneAsync(SimvaScene).completed += ev =>
If there is no "SimvaScene" loaded, it might work on startup, but should fail when after gameplay is launched if the user does not trigger the scene. What's the reasoning on removing loading the "SimvaScene"?

2025-04-25 18:53 UTC, Victorma commented on Runtime/Api/Simva/ApiClient.cs
> +            if(homepage != null) {
Should use "!string.IsNullOrEmpty"

2025-04-25 18:53 UTC, Victorma commented on Runtime/Api/Simva/ApiClient.cs
> +            if(login_hint != null) {
Should use "!string.IsNullOrEmpty"

2025-04-25 18:53 UTC, Victorma commented on Runtime/Api/Simva/ApiClient.cs
> +                dict.Add("homepage", homepage);
Should use "!string.IsNullOrEmpty"

2025-07-10 08:27 UTC, jujusb commented on Runtime/Util/RequestsUtil.cs
> +            while (webRequest.result != UnityWebRequest.Result.ConnectionError && webRequest.result != UnityWebRequest.Result.ProtocolError && webRequest.downloadProgress != 1)
fixed

2025-07-10 08:30 UTC, jujusb commented on Runtime/Runner/SimvaManager.cs
> +                    NotifyManagers("Failed to Login with this token");
fixed

2025-07-10 08:30 UTC, jujusb commented on Runtime/Runner/SimvaManager.cs
> +                    NotifyManagers("Failed to Login with this token");
fixed

2025-07-10 08:32 UTC, jujusb commented on Samples~/Demo/SimvaGameplayTester.cs
> +public class SimvaGameplayTester : MonoBehaviour
fixed

2025-07-10 08:33 UTC, jujusb commented on Runtime/SimvaPlugin.cs
> +            RunScene("gameplay");
fixed

2025-07-10 08:35 UTC, jujusb commented on Runtime/SimvaPlugin.cs
> +            Log("[SIMVA] Starting...");
fixed

2025-07-10 08:35 UTC, jujusb commented on Runtime/SimvaPlugin.cs
> +            Log(name);
fixed

2025-07-10 08:38 UTC, jujusb commented on Runtime/Api/Simva/ApiClient.cs
> +            if(login_hint != null) {
fixed

2025-07-10 08:38 UTC, jujusb commented on Runtime/Api/Simva/ApiClient.cs
> +                dict.Add("homepage", homepage);
fixed

2025-07-10 08:38 UTC, jujusb commented on Runtime/SimvaPlugin.cs
> +                    Log("[SIMVA] Study is not set! Stopping...");
fixed

2025-07-10 08:53 UTC, jujusb commented on Runtime/SimvaPlugin.cs
> -                SceneManager.LoadSceneAsync(SimvaScene).completed += ev =>
The trigger is done now by calling RunScene(Simva.***) in the code of the plugin to run the simva scene and as that we don't need anymore "SceneManager.LoadSceneAsync(SimvaScene).completed += ev =>"

2025-07-15 16:53 UTC, Victorma commented on Runtime/SimvaPlugin.cs
> -                SceneManager.LoadSceneAsync(SimvaScene).completed += ev =>
Although I've checked this does not impact uAdventure, I'm concerned about the SimvaScene because it is a scene that is mostly empty and its used as cleanup. This allows the SimvaPlugin to switch from gameplay to Simva environment when needed having no other game objects in the scene (except those DontDestroyOnLoad). This can avoid collisions with menus, background music, etc.
I would suggest finishing the review and requesting a new feature to allow for loading the simva scenes on a blank scene or additively (as it is right now).

2025-07-15 17:09 UTC, merged